---
version: "3.9"

services:
  3x-ui:
    image: ghcr.io/Taha-Alavi/3x-ui:latest
    container_name: staartvpn
    hostname: yourhostname
    volumes:
      - $PWD/db/:/etc/x-ui/
      - $PWD/cert/:/root/cert/
    environment:
      XRAY_VMESS_AEAD_FORCED: "false"
    tty: true
    network_mode: host
    restart: unless-stopped
